version: '3.5'
services:
  converter:
    build: .
    container_name: vac
    privileged: true
    env_file:
      - secrets.env
    volumes:
      - ./cron/hourly:/etc/cron.hourly
      - ./cron/daily:/etc/cron.daily
      - ./cron/weekly:/etc/cron.weekly
      - ./cron/monthly:/etc/cron.monthly
      - ./cron/reboot:/etc/cron.reboot
      - ./cron/start:/etc/cron.start
      - ./cron/logs:/var/log/cron
    restart: always
