version: '2.0'
services:
  converter:
    build: .
    container_name: vac
    privileged: true
    env_file:
      - secrets.env
    volumes:
      - ./cron.hourly:/etc/cron.hourly
      - ./cron.daily:/etc/cron.daily
      - ./cron.weekly:/etc/cron.weekly
      - ./cron.monthly:/etc/cron.monthly
      - ./cron.reboot:/etc/cron.reboot
      - ./logs:/var/log/cron
    restart: unless-stopped:0
